name: Java CI with GraalVM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Test with Maven
        run: mvn clean package -Pnative

      - name: Add command tests
        run: |
          # Rodamos o exe e guardamos o resultado
          $output = .\target\expense-tracker.exe add -d "Teste Pipeline" -a 100
          
          # Verificamos se a descrição correta aparece no bolo de texto
          if ($output -like "*Description: Teste Pipeline*") { 
            Write-Host "Test passed!" -ForegroundColor Green
          } else { 
            Write-Host "Test failed!" -ForegroundColor Red
            $output | Write-Host
            exit 1 
          }