name: Java CI with GraalVM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Test
        run: mvn clean package -Pnative

      - name: Add command tests#1
        run: |
          # Check for 'Expense added successfully (ID: 1)'
          $output = .\target\expense-tracker.exe add -d "Lunch" -a 20 -c meals
          
          if ($output -like '*Expense added successfully (ID: 1)*') { 
            Write-Host "Test passed!"
            $output | Write-Host
          } else { 
            Write-Host "Test failed!"
            $output | Write-Host
            exit 1 
          }

      - name: Add command tests#2
        run: |
          # Check for 'Expense added successfully (ID: 2)'
          $output = .\target\expense-tracker.exe add -d "Dinner" -a 10 -c meals

          if ($output -like '*Expense added successfully (ID: 2)*') { 
            Write-Host "Test passed!"
            $output | Write-Host
          } else { 
            Write-Host "Test failed!"
            $output | Write-Host
            exit 1 
          }

      - name: List command tests#1
        run: |
          # Check for 'Lunch' and 'Dinner'
          $output = .\target\expense-tracker.exe list

          if ($output -like '*Lunch*' || $output -like '*Dinner*') { 
            Write-Host "Test passed!"
            $output | Write-Host
          } else { 
            Write-Host "Test failed!"
            $output | Write-Host
            exit 1 
          }

      - name: Summary command tests#1
        run: |
          # Check for '# Total expenses: R$30,00'
          $output = .\target\expense-tracker.exe summary

          if ($output -like '*# Total expenses: R$30,00*') { 
            Write-Host "Test passed!"
            $output | Write-Host
          } else { 
            Write-Host "Test failed!"
            $output | Write-Host
            exit 1 
          }

      - name: Delete command tests#1
        run: |
          # Check for 'Expense deleted successfully'
          $output = .\target\expense-tracker.exe delete --id 2

          if ($output -like '*Expense deleted successfully*') { 
            Write-Host "Test passed!"
            $output | Write-Host
          } else { 
            Write-Host "Test failed!"
            $output | Write-Host
            exit 1 
          }

      - name: Summary command tests#2
        run: |
          # Check for '# Total expenses: R$20,00'
          $output = .\target\expense-tracker.exe summary
          
          if ($output -like '*# Total expenses: R$20,00*') { 
            Write-Host "Test passed!"
            $output | Write-Host
          } else { 
            Write-Host "Test failed!"
            $output | Write-Host
            exit 1 
          }